version: "3"
services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "3001:3001"

  frontend:
    build: ./client
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
